# Generated by Django 5.1.7 on 2025-03-22 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_remove_quote_like_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='publisher',
        ),
    ]
