# Generated by Django 5.1.7 on 2025-04-02 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_rename_author_comment_publisher'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='like_numbers',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
