# Generated by Django 5.1.7 on 2025-04-03 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_subcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcomment',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_comments', to='myApp.comment'),
        ),
        migrations.AlterField(
            model_name='subcomment',
            name='quote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.quote'),
        ),
        migrations.AlterField(
            model_name='subcomment',
            name='sub_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_sub_comments', to='myApp.subcomment'),
        ),
    ]
