# Generated by Django 5.1.7 on 2025-04-03 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0007_alter_subcomment_comment_alter_subcomment_quote_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcomment',
            name='quote',
        ),
        migrations.RemoveField(
            model_name='subcomment',
            name='sub_comment',
        ),
        migrations.AddField(
            model_name='subcomment',
            name='parent_subcomment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='myApp.subcomment'),
        ),
        migrations.AlterField(
            model_name='subcomment',
            name='comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sub_comments', to='myApp.comment'),
            preserve_default=False,
        ),
    ]
