# Generated by Django 5.1.7 on 2025-06-20 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0008_remove_subcomment_quote_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='quote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_likes', to='myApp.quote'),
        ),
    ]
