# Generated by Django 5.1.7 on 2025-06-20 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0009_alter_like_quote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='like',
        ),
    ]
